### ISSUE TITLE
Spacing issue in README.md

### ISSUE THREAD

**Issue by jackaitken** [eamon0989/lstimeestimate#11]
In the README file there is an issue with the spacing in the MarkDown file.

_This:_
Welcome to the Launch School Time Estimate This project was created by and is maintained by Launch School Students.

_Should really look like this:_
Welcome to the Launch School Time Estimate.
This project was created by and is maintained by Launch School Students.

Can anyone fix this?

**Comment by mohitsaxenaknoldus** [comment]
Do you still want it fixed? If yes, I can do it.

**Comment by eamon0989** [comment]
Hey that would be great, thank you!

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me.

**Comment by mohitsaxenaknoldus** [comment]
Added PR: https://github.com/eamon0989/lstimeestimate/pull/19
Please review @eamon0989

**Comment by eamon0989** [comment]
Thanks for fixing this @mohitsaxenaknoldus
