### ISSUE TITLE
User should be automatically taken to the bottom of the page after submitting the form

### ISSUE THREAD

**Issue by nina-dk** [eamon0989/lstimeestimate#23]
When the form is submitted, the new list items are created to the bottom of the current list and the user has to scroll down on their own to see it. Instead, the page should automatically scroll down once the new list items have been created.

**Comment by eamon0989** [comment]
Great idea, I think it would depend on the user's screen size though so you would have to detect if its within the viewport or not. Another option would be to insert the new list items at the top of the list instead of at the bottom making them more accessible.

**Comment by eamon0989** [comment]
Great job, you've really cleaned up the code! I especially like how you moved the method invocations into the class constuctor. @nina-dk

**Comment by nina-dk** [comment]
Thanks, Eamon, glad I could help!
