### ISSUE TITLE
Clicking submit twice adds double the divs required at the end

### ISSUE THREAD

**Issue by eamon0989** [eamon0989/lstimeestimate#3]
If submit is clicked a second or third time, either remove the extra divs and add new, or stop the user from clicking more than once

**Comment by jackaitken** [comment]
After the user's average and max estimate `li`'s are added to the `ul`, can we just set `disabled` to `true` on the Submit button?

**Comment by eamon0989** [comment]
That should work, feel free to implement that if you like.

**Comment by eamon0989** [comment]
Update: the button has been changed to a `div` so that won't work anymore,  maybe we could check if those `li`'s have been created and then disable the button using JS unless the input numbers have changed
